/* tslint:disable */
/* eslint-disable */
/**
 * Virki API
 * REST API for the Virki 2FA service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncryptedKeysKek
 */
export interface EncryptedKeysKek {
    /**
     * 
     * @type {any}
     * @memberof EncryptedKeysKek
     */
    hash: any | null;
    /**
     * 
     * @type {any}
     * @memberof EncryptedKeysKek
     */
    salt: any | null;
    /**
     * 
     * @type {any}
     * @memberof EncryptedKeysKek
     */
    opsLimit: any | null;
    /**
     * 
     * @type {any}
     * @memberof EncryptedKeysKek
     */
    memLimit: any | null;
}

/**
 * Check if a given object implements the EncryptedKeysKek interface.
 */
export function instanceOfEncryptedKeysKek(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hash" in value;
    isInstance = isInstance && "salt" in value;
    isInstance = isInstance && "opsLimit" in value;
    isInstance = isInstance && "memLimit" in value;

    return isInstance;
}

export function EncryptedKeysKekFromJSON(json: any): EncryptedKeysKek {
    return EncryptedKeysKekFromJSONTyped(json, false);
}

export function EncryptedKeysKekFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncryptedKeysKek {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'salt': json['salt'],
        'opsLimit': json['opsLimit'],
        'memLimit': json['memLimit'],
    };
}

export function EncryptedKeysKekToJSON(value?: EncryptedKeysKek | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'salt': value.salt,
        'opsLimit': value.opsLimit,
        'memLimit': value.memLimit,
    };
}

