/* tslint:disable */
/* eslint-disable */
/**
 * Virki API
 * REST API for the Virki 2FA service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenPeriod
 */
export interface TokenPeriod {
}

/**
 * Check if a given object implements the TokenPeriod interface.
 */
export function instanceOfTokenPeriod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenPeriodFromJSON(json: any): TokenPeriod {
    return TokenPeriodFromJSONTyped(json, false);
}

export function TokenPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPeriod {
    return json;
}

export function TokenPeriodToJSON(value?: TokenPeriod | null): any {
    return value;
}

