/* tslint:disable */
/* eslint-disable */
/**
 * Virki API
 * REST API for the Virki 2FA service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenAlgorithm
 */
export interface TokenAlgorithm {
}

/**
 * Check if a given object implements the TokenAlgorithm interface.
 */
export function instanceOfTokenAlgorithm(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenAlgorithmFromJSON(json: any): TokenAlgorithm {
    return TokenAlgorithmFromJSONTyped(json, false);
}

export function TokenAlgorithmFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenAlgorithm {
    return json;
}

export function TokenAlgorithmToJSON(value?: TokenAlgorithm | null): any {
    return value;
}

