FROM node:20-alpine

WORKDIR /app

# Install Git
RUN apk add git

# Copy package.json and Yarn lockfile
COPY package.json .
COPY yarn.lock .
RUN yarn install

# Copy the project files into the working directory (/app)
COPY . .

# Start the development server on the default Vite port
CMD ["yarn", "dev"]